services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    image: koda_api
    container_name: koda_api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./backend/.envs/.env.prod
    depends_on:
      - postgres
      - redis
    command: /start
    networks:
      - reverseProxy_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    image: koda_postgres
    container_name: koda_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.envs/.env.prod
    networks:
      - reverseProxy_nw

  client:
    build:
      context: .
      dockerfile: ./docker/prod/client/Dockerfile
    container_name: koda_client
    image: koda_client
    env_file:
      - "./client/.env.prod"
    networks:
      - reverseProxy_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: koda_redis
    volumes:
      - redis_data:/data
    networks:
      - reverseProxy_nw

  # enketo:
  #   image: ghcr.io/enketo/enketo:7.6.1
  #   container_name: koda_enketo
  #   expose:
  #      - "8005"
  #   volumes:
  #      - ./docker/prod/enketo/config.json:/srv/src/enketo/packages/enketo-express/config/config.json
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  #   networks:
  #     - reverseProxy_nw

  celeryworker:
    <<: *api
    image: koda_celeryworker
    container_name: koda_celeryworker
    command: /start-celeryworker

 celerybeat:
   image: koda_celerybeat
   container_name: koda_celerybeat
   build:
     context: .
     dockerfile: ./docker/prod/django/Dockerfile
   command: /start-celerybeat
   volumes:
     - static_volume:/app/staticfiles
   env_file:
     - ./backend/.envs/.env.prod
   depends_on:
     - redis
     - postgres
   networks:
     - reverseProxy_nw

  flower:
    <<: *api
    image: koda_flower
    container_name: koda_flower
    ports:
      - "5555:5555"
    command: /start-flower


networks:
    reverseProxy_nw:
        external: true

volumes:
  media_volume:
  static_volume:
  postgres_data:
  redis_data:
